### ISSUE TITLE
While adding a media to a wyzywig I can no more press on it to edit it or change it

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#80] opened 2024-11-05 14:46 UTC
- [ ] While adding a media to a wyzywig I can no more press on it to edit it or change it

### **Acceptance testing**

- [ ] When adding a media to a wyzywig I need to be able click on it and have it open in the media meta component to edit it or modify it

**Comment by jfayad** [comment] 2024-11-08 04:50
duplicate of #33 ?

**Closed by jfayad** 2024-11-08 04:50 UTC
